esphome:
  name: esp01-relay
  friendly_name: esp01-relay

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nXYigbqX6CwZew6FXhyFUweNw4TAs/qZImEsJlot8Fg="

ota:
  password: "315d41f7dd962531fffbe818530539a3"

# # 开启Web服务器 (可选)
# web_server:
#   port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01-Relay Fallback Hotspot"
    password: "8IxVDDeosXxF"

captive_portal:

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO0