esphome:
  name: esp32-album
  friendly_name: esp32_album

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2h8QFwM0jyoaBkkkZfd7hhMnpdC5Q4HKJzYFNwChqgs="

ota:
  password: "5740643b4226710be299eb75be43a095"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Album Fallback Hotspot"
    password: "TCs31SFJql4x"

captive_portal:


spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
    
font:
  - file: "fonts/Roboto-Regular.ttf"
    id: my_font
    size: 14

image:
  - file: "imgs/cat.bmp"
    type: RGB24
    id: cat
    resize: 80x80
  - file: "imgs/cat160x80.bmp"
    type: RGB24
    id: cat2
    resize: 160x80

# Example minimal configuration entry
display:
  - platform: st7735
    model: "INITR_MINI160X80"
    cs_pin: GPIO5
    dc_pin: GPIO2
    reset_pin: GPIO4
    rotation: 270
    device_width: 80
    device_height: 160
    col_start: 26
    row_start: 0
    use_bgr: True
    invert_colors: True
    eight_bit_color: False
    update_interval: 5s
    lambda: |-
      it.fill(Color::BLACK);
      it.image(0, 0, id(cat2));
      it.print(0, 0, id(my_font), "Hello World!");
