esphome:
  name: esp8266_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # 使用IP静态分配 (可选)
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # 启用降级连接 (可选)
  use_address: 192.168.1.100

# 开启日志记录
logger:

# 开启Web服务器 (可选)
web_server:
  port: 80

# 启用Home Assistant API
api:

# OTA升级
ota:

# 配置DHT传感器
sensor:
  - platform: dht
    pin: D2
    temperature:
      id: temperature
      name: "Living Room Temperature"
    humidity:
      id: humidity
      name: "Living Room Humidity"
    update_interval: 60s
    model: DHT11

switch:
  - platform: gpio
    pin: D6
    name: "Relay Switch"
    id: relay_switch
    
spi:
  clk_pin: D5
  mosi_pin: D7

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
    
font:
  - file: "fonts/Roboto-Regular.ttf"
    id: my_font
    size: 14

image:
  - file: "imgs/cat.bmp"
    type: RGB24
    id: cat
    resize: 128x128

# Example minimal configuration entry
display:
  - platform: st7735
    model: "INITR_18BLACKTAB"
    cs_pin: D8
    dc_pin: D3
    reset_pin: D4
    rotation: 0
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: False
    update_interval: 5s
    lambda: |-
      it.fill(Color::BLACK);
      it.print(0, 0, id(my_font), "Hello World!");
      if (id(temperature).has_state()) {
        it.printf(0, 20, id(my_font), id(my_green), TextAlign::TOP_LEFT, "Temp: %.1f°C", id(temperature).state);
      }
      it.image(0, 40, id(cat));
